name: Sync To Gitee
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: wearerequired/git-mirror-action@master 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/duicikeyihangaolou/training-python-public.git"
          destination-repo: "git@gitee.com:wu-wen-xiang/training-python.git"
